# Generated by Django 5.1.6 on 2025-02-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prueba',
            options={'verbose_name': 'Prueba', 'verbose_name_plural': 'Pruebas'},
        ),
    ]
