# Generated by Django 5.1.6 on 2025-02-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_prueba_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=205)),
                ('descripción', models.CharField(max_length=200)),
                ('img_ubi', models.CharField(max_length=200)),
                ('foto_bool', models.BooleanField(default=True)),
            ],
        ),
    ]
