# Generated by Django 5.1.6 on 2025-02-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
