# Generated by Django 5.1.6 on 2025-03-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_galeria_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripción', models.CharField(max_length=1000)),
                ('objetivo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
    ]
