# Generated by Django 5.1.6 on 2025-03-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_solicitudes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('área', models.CharField(max_length=100)),
                ('descripción', models.CharField(max_length=1000)),
                ('requisitos', models.CharField(max_length=500)),
                ('horario', models.CharField(max_length=100)),
                ('paga', models.CharField(max_length=100)),
            ],
        ),
    ]
