# Generated by Django 5.1.6 on 2025-03-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_empleos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empleos')),
            ],
        ),
    ]
