# Generated by Django 5.1.6 on 2025-03-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_solicitud_empleo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripción', models.CharField(max_length=1000)),
                ('formato', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('arch_ubi', models.CharField(max_length=100)),
            ],
        ),
    ]
